import type { Brief, Card, Critique, Project } from '../domain/cardnews.js';
import type { CreativeDirector, ImageArtist, VisualCritic } from '../application/ports.js';
import { DemoCreativeDirector, DemoImageArtist, DemoVisualCritic } from './demo-ai.js';
export class OpenAICreativeDirector implements CreativeDirector{
 private demo=new DemoCreativeDirector(); constructor(private key:string,private model=process.env.OPENAI_TEXT_MODEL||'gpt-5-mini'){}
 private async json(prompt:string){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${this.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:this.model,input:prompt,text:{format:{type:'json_object'}}})});if(!r.ok)throw new Error(`OpenAI ${r.status}`);const j:any=await r.json();return JSON.parse(j.output_text);}
 async direct(b:Brief){try{const fallback=await this.demo.direct(b);const prompt=`당신은 한국 수학교육 카드뉴스의 Creative Director다. 다음 브리프를 7장짜리 프리미엄 인스타그램 카드뉴스로 기획하라. 고정 템플릿을 반복하지 말고 한 가지 관점과 서사를 만든다. 한국어 문장은 짧고 정확해야 한다. JSON만 반환: {title,strategy,cards:[{role,eyebrow,headline,body,accent,art:{layout:editorial|diagram|split|statement,palette:[hex,hex,hex],visualPrompt}}]}. brief=${JSON.stringify(b)}`;const x=await this.json(prompt);return {...fallback,...x,cards:x.cards.map((c:any,i:number)=>({...fallback.cards[i],...c,id:fallback.cards[i].id,status:'ready'}))};}catch(e){if(process.env.ALLOW_DEMO_FALLBACK==='false')throw e;return this.demo.direct(b);}}
 async redesign(b:Brief,c:Card,instruction?:string){try{const x=await this.json(`이 카드만 더 강하게 재기획하라. JSON Card 반환. brief=${JSON.stringify(b)} card=${JSON.stringify(c)} request=${instruction||'자율 개선'}`);return {...c,...x,id:c.id,status:'ready'};}catch(e){if(process.env.ALLOW_DEMO_FALLBACK==='false')throw e;return this.demo.redesign(b,c,instruction);}}
}
export class OpenAIImageArtist implements ImageArtist{private demo=new DemoImageArtist();constructor(private key:string,private model=process.env.OPENAI_IMAGE_MODEL||'gpt-image-1'){}async create(c:Card,b:Brief){if(c.art.layout==='statement')return undefined;try{const r=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${this.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:this.model,prompt:`${c.art.visualPrompt}. Instagram editorial artwork for Korean math academy. Absolutely no letters, words, numbers or logos.`,size:'1024x1536',quality:'medium'})});if(!r.ok)throw new Error(`Image ${r.status}`);const j:any=await r.json();return `data:image/png;base64,${j.data[0].b64_json}`;}catch(e){if(process.env.ALLOW_DEMO_FALLBACK==='false')throw e;return this.demo.create(c,b);}}}
export class OpenAIVisualCritic implements VisualCritic{private demo=new DemoVisualCritic();constructor(private key:string){}async critique(p:Project,previews?:string[]):Promise<Critique>{return this.demo.critique(p,previews);}}
