import{useEffect,useMemo,useRef,useState}from'react';import{ArrowLeft,ArrowRight,Download,Lightbulb,RefreshCw,Sparkles,WandSparkles,X}from'lucide-react';import{api}from'./api';import{CardCanvas}from'./CardCanvas';import type{Brief,Card,Critique,Project}from'./types';
const types=[['study-strategy','공부법·학습전략'],['problem-solving','문제풀이·사고법'],['concept-strategy','개념·단원전략'],['academy-story','학원·수업소개'],['student-growth','학생 성장·결과']] as const;
const initial:Brief={topic:'',type:'study-strategy',tone:'student-friendly',academyName:'생각하는 수학',audience:'고등학생'};
export default function App(){const[brief,setBrief]=useState(initial);const[project,setProject]=useState<Project>();const[active,setActive]=useState(0);const[busy,setBusy]=useState(false);const[progress,setProgress]=useState(0);const[stage,setStage]=useState('');const[ideas,setIdeas]=useState<string[]>([]);const[showIdeas,setShowIdeas]=useState(false);const[critique,setCritique]=useState<Critique>();const cardRef=useRef<HTMLDivElement>(null);
 const valid=brief.topic.trim().length>=3&&brief.academyName.trim();
 async function generate(){if(!valid)return;setBusy(true);setProgress(4);setStage('브리프를 읽고 있어요');setCritique(undefined);const timer=setInterval(()=>setProgress(p=>{const n=Math.min(p+Math.max(1,Math.round((90-p)/9)),90);setStage(n<25?'콘텐츠 전략을 세우고 있어요':n<48?'7장 스토리를 설계하고 있어요':n<75?'장면별 비주얼을 만들고 있어요':'문장과 브랜드를 합성하고 있어요');return n}),450);try{const p=await api.create(brief);clearInterval(timer);setProgress(100);setStage('완성');setProject(p);setActive(0)}catch(e){alert(e instanceof Error?e.message:'생성 실패')}finally{clearInterval(timer);setTimeout(()=>setBusy(false),450)}}
 async function openIdeas(){if(!ideas.length)setIdeas(await api.ideas());setShowIdeas(true)}
 function updateCard(patch:Partial<Card>){if(!project)return;setProject({...project,cards:project.cards.map((c,i)=>i===active?{...c,...patch}:c)})}
 async function redesign(){if(!project)return;setBusy(true);setStage(`${active+1}번 카드만 다시 디자인하고 있어요`);setProgress(25);try{const c=await api.redesign(project.brief,project.cards[active]);setProgress(100);updateCard(c)}finally{setBusy(false)}}
 async function review(){if(!project)return;setBusy(true);setStage('완성 이미지를 비평하고 있어요');setProgress(40);try{setCritique(await api.critique(project));setProgress(100)}finally{setBusy(false)}}
 async function download(){if(!cardRef.current)return;const {toPng}=await import('html-to-image');const url=await toPng(cardRef.current,{pixelRatio:1,canvasWidth:1080,canvasHeight:1350});const a=document.createElement('a');a.href=url;a.download=`cardnews-${active+1}.png`;a.click()}
 const selected=project?.cards[active];const totalCost=project?project.usage.estimatedTextCost+project.usage.estimatedImageCost:0;
 return <main><header><div className="logo"><span><Sparkles size={17}/></span><div><b>CARDNEWS STUDIO</b><small>AI CREATIVE DIRECTOR · 2.0</small></div></div>{project&&<button className="ghost" onClick={()=>setProject(undefined)}>새 프로젝트</button>}</header>
 {!project?<section className="landing"><div className="intro"><p className="kicker">FROM IDEA TO PUBLISH-READY</p><h1>좋은 카드뉴스는<br/><em>디자인보다 생각</em>에서 시작합니다.</h1><p>주제 하나만 적어주세요. 콘텐츠 전략부터 7장의 흐름, 장면별 아트디렉션과 검수까지 한 번에 만듭니다.</p></div><div className="brief-panel"><label>무엇에 대한 카드뉴스인가요?</label><div className="topic"><textarea value={brief.topic} onChange={e=>setBrief({...brief,topic:e.target.value})} placeholder="예: 오답노트를 열심히 써도 성적이 오르지 않는 이유"/><button onClick={openIdeas}><Lightbulb size={17}/> 주제 아이디어</button></div><label>카드 유형</label><div className="type-grid">{types.map(([v,l])=><button key={v} className={brief.type===v?'active':''} onClick={()=>setBrief({...brief,type:v})}>{l}</button>)}</div><div className="split-fields"><div><label>말투</label><select value={brief.tone} onChange={e=>setBrief({...brief,tone:e.target.value as Brief['tone']})}><option value="student-friendly">학생 친화적</option><option value="teacher-expert">교사 전문적</option><option value="parent-friendly">학부모 친화적</option></select></div><div><label>대상</label><select value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})}><option>중학생</option><option>고1</option><option>고2</option><option>고3</option><option>학부모</option><option>고등학생</option></select></div></div><label>학원명</label><input value={brief.academyName} onChange={e=>setBrief({...brief,academyName:e.target.value})}/><button className="generate" disabled={!valid||busy} onClick={generate}><WandSparkles/> 7장 카드뉴스 만들기</button></div></section>:
 <section className="studio"><aside><button className="back" onClick={()=>setProject(undefined)}><ArrowLeft size={16}/> 브리프</button><p className="kicker">STORYBOARD</p><h3>{project.title}</h3><p className="strategy">{project.strategy}</p><div className="thumbs">{project.cards.map((c,i)=><button key={c.id} className={i===active?'selected':''} onClick={()=>setActive(i)}><span>{i+1}</span><div><b>{c.role}</b><small>{c.headline.replace('\n',' ')}</small></div></button>)}</div><div className="cost"><span>예상 생성 비용</span><b>₩{totalCost.toLocaleString()}</b><small>텍스트 ₩{project.usage.estimatedTextCost} · 이미지 ₩{project.usage.estimatedImageCost}</small></div></aside><div className="preview"><div className="preview-bar"><div><b>{active+1} / {project.cards.length}</b><span>{selected?.role}</span></div><div><button onClick={redesign}><RefreshCw size={16}/> 이 페이지만 재디자인</button><button onClick={download}><Download size={16}/> PNG</button></div></div>{selected&&<CardCanvas ref={cardRef} card={selected} index={active} total={project.cards.length} academy={brief.academyName}/>}<div className="pager"><button disabled={active===0} onClick={()=>setActive(x=>x-1)}><ArrowLeft/></button><div>{project.cards.map((_,i)=><i key={i} className={i===active?'on':''}/>)}</div><button disabled={active===project.cards.length-1} onClick={()=>setActive(x=>x+1)}><ArrowRight/></button></div></div><aside className="editor"><p className="kicker">CARD EDITOR</p><label>작은 제목</label><input value={selected?.eyebrow||''} onChange={e=>updateCard({eyebrow:e.target.value})}/><label>핵심 제목</label><textarea value={selected?.headline||''} onChange={e=>updateCard({headline:e.target.value})}/><label>본문</label><textarea className="body-field" value={selected?.body||''} onChange={e=>updateCard({body:e.target.value})}/><label>강조 단어</label><input value={selected?.accent||''} onChange={e=>updateCard({accent:e.target.value})}/><button className="critic" onClick={review}><Sparkles size={17}/> 실제 결과물 AI 검수</button>{critique&&<div className="review"><b>{critique.score}점</b><p>{critique.summary}</p>{critique.issues.filter(x=>x.cardId===selected?.id).map((x,i)=><small key={i}>{x.message}</small>)}</div>}</aside></section>}
 {busy&&<div className="overlay"><div className="progress-card"><div className="spinner"><Sparkles/></div><h3>{stage}</h3><div className="progress"><i style={{width:`${progress}%`}}/></div><b>{progress}%</b><small>창을 닫지 않아도 다른 작업을 할 수 있어요.</small></div></div>}{showIdeas&&<div className="modal-bg"><div className="modal"><button className="close" onClick={()=>setShowIdeas(false)}><X/></button><p className="kicker">TOPIC STARTERS</p><h2>저장하고 싶은 주제로 시작하세요</h2>{ideas.map(x=><button className="idea" key={x} onClick={()=>{setBrief({...brief,topic:x});setShowIdeas(false)}}>{x}<ArrowRight size={16}/></button>)}</div></div>}</main>}
